### ISSUE TITLE
windows binaries?

### ISSUE THREAD

**Issue by bgoli** [equaeghe/ecyglpki#8]
Hi

Thanks for a great project, I was wondering if anybody had tried building ecyglpki on windows.

Brett

**Comment by equaeghe** [comment]
I haven't tried (I don't have a Windows machine), but as far as I know there are no UNIX-specific parts, so it should work. Have you tried? Did you get some errors?

**Comment by bgoli** [comment]
Thanks. I've been experiencing GLPK compilation issues with some of the Windows toolchains but should have something to test soon.

**Comment by bgoli** [comment]
I eventually managed to compile everything but couldn't get this stable enough to use, mostly due to GCC and Windows dependency/linking issues but will keep it on the todo list, Linux performance is great so I'll use that for now.
